<?php
/** @var string $id_editar */
/** @var array $secciones */
/** @var object|null $user */
?>

<?php if ($user && $user->rol === 'admin'): ?>
    <form action="modificar/<?= $id_editar ?>" method="POST">
        
        <input type="text" name="editar_titulo" placeholder="Nuevo Título" required>
        <input type="text" name="editar_cuerpo" placeholder="Nuevo Cuerpo" required>
        <input type="date" name="editar_fecha" required>
        
        <select name="editar_id_seccion_fk" required>
            <option value="">-- Elegí una sección --</option>
            <?php foreach ($secciones as $seccion): ?>
                <option value="<?= $seccion->id_seccion ?>">
                    <?= $seccion->nombre ?>
                </option>
            <?php endforeach; ?>
        </select>

        <button type="submit" class="btn-add">Modificar Noticia</button>
    </form>
<?php endif; ?>